### ISSUE TITLE
Fix admin desciption media link

### ISSUE THREAD

**Issue by 8sd** [asepart/amosss182#151]

**Comment by longpdo** [comment]
What was the actual problem here?

**Comment by 8sd** [comment]
The link of media in the ticket description is appended to the current url instead of just loading the url

**Comment by longpdo** [comment]
fixed this in commit e3a44d98d9c0625ae6bcf2e6b14f66257da6acfb

since you used Link from react-router-dom u always had the current link of the current component attached in front of the actual file link.
