### ISSUE TITLE
Install apk on all phones

### ISSUE THREAD

**Issue by 8sd** [asepart/amosss182#153]

**Comment by longpdo** [comment]
little problem for the iphone users....apk's can only be installed on android phones to my knowledge

**Comment by dimonco** [comment]
We only did apk because Android was the first priority.

**Comment by markrudtke** [comment]
That means iphone users can only demo with expo, right?

**Comment by dimonco** [comment]
If you can run react-native run-ios and it works, then we're in luck :)

**Comment by dimonco** [comment]
So, can anybody try this on iOS? It's not my fault that these "nice people" from Apple are so closed-minded and made it possible only on MacOS

**Comment by davidhaller** [comment]
I do not own an iPhone or Macintosh computer, so I can not test.

**Comment by longpdo** [comment]
![bildschirmfoto 2018-07-10 um 09 58 32](https://user-images.githubusercontent.com/33006592/42496969-fd46c420-8427-11e8-87c0-2bd0bcd800fa.png)

npm run ios 
react-native run ios 
does not work

tested this with the 80s branch and npm installed before trying out the ios command

**Comment by longpdo** [comment]
![bildschirmfoto 2018-07-10 um 11 28 47](https://user-images.githubusercontent.com/33006592/42501732-a84886a4-8434-11e8-98ea-d758fb3822a2.png)

npm run ios does work

one is able to use expo to test it 

but returns an error right now when you open the userapp

**Comment by markrudtke** [comment]
Ok, since we only have apk's for android I would suggest that all iPhone users use the expo app for the demo. @longpdo, @tanjabatz, are you ok with that?

**Comment by longpdo** [comment]
yeah

**Comment by davidhaller** [comment]
Final apk file is available. Don't forget to install.
