### ISSUE TITLE
Database Consistency Problems

### ISSUE THREAD

**Issue by davidhaller** [asepart/amosss182#31]
The ticketName attribute of Ticket is not unique, so by creating two tickets with the same name and adding at least one of the tickets to a Project, the database would be in an inconsistent state.

Also, Ticket should be an weak entity with an many-to-one relationship to Project.

Admins and Users are in separate tables, so two different human users can have the same account name if they are in different roles.

We should probably make the switch to a sane database solution that prevents such design flaws.

**Comment by davidhaller** [comment]
Using ticketId instead of ticketName since pull request #32, so this is partly resolved.

**Comment by markrudtke** [comment]
Ok, thank you!

**Comment by davidhaller** [comment]
This is not done yet. Ticket must be transformed to an weak entity. Otherwise you could assign one ticket to multiple projects which makes no sense.

**Comment by markrudtke** [comment]
I've tried some approaches, but they all failed. Could you help me with that?

**Comment by markrudtke** [comment]
Ok, just a second. Could it just be adding unique in Ticket here:
`@Column(name = "ticket_name", nullable = false, unique = true)`

**Comment by davidhaller** [comment]
Then you would not be able to create ticket with the same name - even on different projects. No, ticketId is there primary key and should be used to identify tickets, this is already done.

What still needs to be done is to delete the ProjectTicket class and add a projectName attribute to Ticket, because it is a n:1 relationship and not n:m.

**Comment by davidhaller** [comment]
And then there is the problem with Admin and Users. There could be an Admin named Jon Doe and a user named Jon Doe (both different natural persons behind), comment on the same Ticket and you could not tell the difference.

**Comment by markrudtke** [comment]
-Of course, since a ticket is only existing within a project, we don't need the ProjectTicket anymore. I changed that.
-I think this belongs to chat/account management. On such a case, couldn't you just show the role of each account? Then you could tell the difference: "Jon Doe (Admin)" vs. "Jon Doe (User)". Do you have another idea?

**Comment by davidhaller** [comment]
Ticket is weak entity now, but the Admin/User thing is still open. The problem is that we do not save in the database currently if "Jon Doe (Admin)" or "Jon Doe (User)" wrote it so frontend cannot know.

**Comment by davidhaller** [comment]
All issues resolved. I simple forbid to create an user and an admin with the same login name.
